[package]
name = "i18n-puzzles-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
encoding_rs = "0.8.35"
deunicode = "1.6.0"
hex = "0.4.3"
itertools = "0.14.0"
jiff = "0.2.3"
kanji-number-parser = "0.1.0"
unicode-normalization = "0.1.24"